name: "${project.artifactId}"
main: "${project.groupId}.${project.artifactId}"
version: "${project.version}"
description: "${project.artifactId} Bukkit Plugin"
author: "BillyGalbreath"
api-version: "1.13"

commands:
  mobdrops:
    description: Reload configs
    permission: command.mobdrops
    usage: /<command> (reload)

permissions:
  command.mobdrops:
    description: Allows to reload configs
    default: op
