name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: ${project.artifactId} Bukkit Plugin
author: BillyGalbreath
softdepend:
- EntityData

commands:
    mobdrops:
        description: Reload configs
        usage: /<command> (reload)

permissions:
    command.moddrops:
        description: Allows to reload configs
        default: op
